### ISSUE TITLE
Tesla_Powerwall module not found after re-install of Plugin

### ISSUE THREAD

**Issue by trundle57** [Panda88CO/udi-TeslaPowerWall#6]
I had to change my powerwall and tesla cloud passwords and ended up deleting the plugin from the AC and then re-installing.  Now, I get the following error when starting TeslaPowerwall
 
2024-01-31 10:34:26,566 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
  File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaPWController.py", line 5, in <module>
    from  TeslaInfo import tesla_info
  File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaInfo.py", line 14, in <module>
    from tesla_powerwall import Powerwall, GridStatus, OperationMode, MeterType
ModuleNotFoundError: No module named 'tesla_powerwall'

Any assistance would be appreciated. 

-Tom

**Comment by Panda88CO** [comment]
Let me take a look - API may have been updated
Christian
________________________________
From: trundle57 ***@***.***>
Sent: Wednesday, January 31, 2024 8:38 AM
To: Panda88CO/udi-TeslaPowerWall ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Panda88CO/udi-TeslaPowerWall] Tesla_Powerwall module not found after re-install of Plugin (Issue #6)


I had to change my powerwall and tesla cloud passwords and ended up deleting the plugin from the AC and then re-installing. Now, I get the following error when starting TeslaPowerwall

2024-01-31 10:34:26,566 MainThread udi_interface ERROR udi_interface:write: Traceback (most recent call last):
File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaPWController.py", line 5, in
from TeslaInfo import tesla_info
File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaInfo.py", line 14, in
from tesla_powerwall import Powerwall, GridStatus, OperationMode, MeterType
ModuleNotFoundError: No module named 'tesla_powerwall'

Any assistance would be appreciated.

-Tom

**Comment by Panda88CO** [comment]
can you send me the system log as well - It seems like it cannot find the tesla_powerwall
I updated it to use the version I have tested - Can you try to reinstall


________________________________
From: trundle57 ***@***.***>
Sent: Wednesday, January 31, 2024 8:38 AM
To: Panda88CO/udi-TeslaPowerWall ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Panda88CO/udi-TeslaPowerWall] Tesla_Powerwall module not found after re-install of Plugin (Issue #6)


I had to change my powerwall and tesla cloud passwords and ended up deleting the plugin from the AC and then re-installing. Now, I get the following error when starting TeslaPowerwall

2024-01-31 10:34:26,566 MainThread udi_interface ERROR udi_interface:write: Traceback (most recent call last):
File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaPWController.py", line 5, in
from TeslaInfo import tesla_info
File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaInfo.py", line 14, in
from tesla_powerwall import Powerwall, GridStatus, OperationMode, MeterType
ModuleNotFoundError: No module named 'tesla_powerwall'

Any assistance would be appreciated.

-Tom

**Comment by trundle57** [comment]
I deleted the plugin using the AC and did a new install to the same slot (3) and the same error message repeats on startup.

2024-01-31 16:16:58,964 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: User=0021b9026178_3
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: Home=/var/polyglot/pg3/ns/0021b9026178_3
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/var/polyglot/pg3/ns/0021b9026178_3
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MjE6Yjk6MDI6NjE6NzgiLCJwcm9maWxlTnVtIjozLCJsb2dMZXZlbCI6IkRFQlVHIiwidG9rZW4iOiJBQTRSdSgqeEcvdHhwMFR5IiwibXF0dEhvc3QiOiJsb2NhbGhvc3QiLCJtcXR0UG9ydCI6ODg4Mywic2VjdXJlIjoxLCJpc1BHM3giOnRydWUsInBnM1ZlcnNpb24iOiIzLjIuMTciLCJpc3lWZXJzaW9uIjoiNS44LjAiLCJlZGl0aW9uIjoiRnJlZSJ9
2024-01-31 16:16:58,964 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2024-01-31 16:16:59,015 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2024-01-31 16:16:59,540 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2024-01-31 16:16:59,777 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2024-01-31 16:16:59,778 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2024-01-31 16:16:59,778 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2024-01-31 16:16:59,778 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2024-01-31 16:16:59,778 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2024-01-31 16:16:59,778 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.6 Starting...
2024-01-31 16:16:59,780 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
  File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaPWController.py", line 5, in <module>
    from  TeslaInfo import tesla_info
  File "/var/polyglot/pg3/ns/0021b9026178_3/TeslaInfo.py", line 14, in <module>
    from tesla_powerwall import Powerwall, GridStatus, OperationMode, MeterType
ModuleNotFoundError: No module named 'tesla_powerwall'

I attached the log package from IoX.  Did you need the log file from the Eisy as well?

Thanks,

Tom
________________________________

**Comment by Panda88CO** [comment]
Sorry - I do not see the attachment

**Comment by trundle57** [comment]
I think the attachment is getting stripped out by GitHub.  I try to send in the app.

My email is ***@***.*** if we can communicate direct.

Tom
________________________________

**Comment by Panda88CO** [comment]
You can also send using universal devices Christian OlgaardSent and "auto corrected" by my iPhoneOn Jan 31, 2024, at 17:55, trundle57 ***@***.***> wrote:﻿
I think the attachment is getting stripped out by GitHub.  I try to send in the app.



My email is ***@***.*** if we can communicate direct.



Tom

________________________________

From: Panda88CO ***@***.***>

Sent: Wednesday, January 31, 2024 4:45:36 PM

To: Panda88CO/udi-TeslaPowerWall ***@***.***>

Cc: trundle57 ***@***.***>; Author ***@***.***>

Subject: Re: [Panda88CO/udi-TeslaPowerWall] Tesla_Powerwall module not found after re-install of Plugin (Issue #6)





Sorry - I do not see the attachment

**Comment by trundle57** [comment]
OneDrive link to the zip file

-tom

[https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20210511.003/assets/item-types/16/zip.svg]https://1drv.ms/u/s!Av6QQ7WfiacRmWMBVX8D1e9W938U



________________________________

**Comment by Panda88CO** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by trundle57** [comment]
OK.  Trying from within GitHub.  I'm a newbie on this platform so forgive me. 
 
[TeslaPW_1-31-2024_40735_PM.zip](https://github.com/Panda88CO/udi-TeslaPowerWall/files/14123398/TeslaPW_1-31-2024_40735_PM.zip)

[ISY Error Log.v5.8.0__Thu 2024.02.01 04.06.22 AM.txt](https://github.com/Panda88CO/udi-TeslaPowerWall/files/14123527/ISY.Error.Log.v5.8.0__Thu.2024.02.01.04.06.22.AM.txt)

-Tom

**Comment by Panda88CO** [comment]
that works
I found a typo in my setup file
Try now
Christian
________________________________

**Comment by trundle57** [comment]
That got the plugin connected but it only created the Powerwall INFO node on my IoX  (EISY).   Is there something else that needs to be done to get the rest of the available nodes configured?


Thanks!

-Tom




________________________________

**Comment by trundle57** [comment]
Never mind.  I stopped the plugin, reinstalled, restarted and all available nodes were created in IoX.  

Thanks so much for your help!

-Tom

**Comment by Panda88CO** [comment]
👍Christian OlgaardSent and "auto corrected" by my iPhoneOn Feb 1, 2024, at 15:44, trundle57 ***@***.***> wrote:﻿
Never mind.  I stopped the plugin, reinstalled, restarted and all available nodes were created in IoX.
Thanks so much for your help!
-Tom
